### ISSUE TITLE
JSONDecodeError in semgrep-action

### ISSUE THREAD

**Issue by colleend** [returntocorp/semgrep#3371]
**Describe the bug**
User is experiencing a JSONDecodeError when running semgrep-action during their attempt to integrate into CI/CD pipeline:

```Run returntocorp/semgrep-action@v1
2
  with:
3
    auditOn: push
4
    publishToken: ***
5
    publishDeployment: 1517
6
/usr/bin/docker run --name returntocorpsemgrepagentv1_c9c082 --label 8a33c1 --workdir /github/workspace --rm -e INPUT_AUDITON -e INPUT_PUBLISHTOKEN -e INPUT_PUBLISHDEPLOYMENT -e INPUT_CONFIG -e INPUT_GENERATESARIF -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/bbcron-user-service/bbcron-user-service":"/github/workspace" returntocorp/semgrep-agent:v1
7
| versions          - semgrep 0.55.1 on Python 3.9.5
8
| environment       - running in environment github-actions, triggering event is 'push'
9
| policy            - using Security Policy, Starter Policy
10
| manage            - logged in as deployment #1517
11
=== setting up agent configuration
12
| using 810 semgrep rules configured on the web UI
13
| using 475 code asset inventory rules
14
| using path ignore rules from .semgrepignore
15
| found 164 files in the paths to be scanned
16
| skipping 3 files based on path ignore rules
17
=== looking for current issues in 161 files
18
An unexpected error occurred
19
ERROR:root:Expecting value: line 1 column 1 (char 0)
20
Traceback (most recent call last):
21
  File "/app/src/semgrep_agent/main.py", line 158, in main
22
    protected_main(**locals())
23
  File "/app/src/semgrep_agent/main.py", line 329, in protected_main
24
    results = semgrep.scan(
25
  File "/app/src/semgrep_agent/semgrep.py", line 295, in scan
26
    findings = get_findings(
27
  File "/app/src/semgrep_agent/semgrep.py", line 146, in get_findings
28
    semgrep_results = invoke_semgrep(
29
  File "/app/src/semgrep_agent/semgrep.py", line 250, in invoke_semgrep
30
    parsed_output = json.load(f)
31
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
32
    return loads(fp.read(),
33
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
34
    return _default_decoder.decode(s)
35
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
36
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
37
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
38
    raise JSONDecodeError("Expecting value", s, err.value) from None
39
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

```
A new version of Semgrep is available. Please see https://github.com/returntocorp/semgrep#upgrading for more information.
26
running 0 rules...
27
28
29
Error: ROR] `/root/.local/bin/semgrep --skip-unknown-extensions --json --config /tmp/tmp73hmquu_.yml README.md mvnw.cmd user-service.iml build.gradle Dockerfile assets/img/2021-02-21_17h31_30.png assets/img/BBcron_addRole.png 'assets/img/bbcron-user-Create User.png' assets/img/bbcron-user-Login.png assets/img/bbcron-user-Tools.png assets/img/2021-02-21_17h31_00.png assets/bbcron-user-service.drawio mvnw src/main/java/com/bbcron/userservice/JWTAuthorizationFilter.java src/main/java/com/bbcron/userservice/service/UserService.java src/main/java/com/bbcron/userservice/service/UserServiceImpl.java src/main/java/com/bbcron/userservice/config/BBCronKeycloakConfig.java src/main/java/com/bbcron/userservice/dto/UserProfileDto.java src/main/java/com/bbcron/userservice/dto/UserDto.java src/main/java/com/bbcron/userservice/controller/BBCronUserController.java src/main/java/com/bbcron/userservice/repository/UserRepository.java src/main/java/com/bbcron/userservice/exceptions/RestResponseBBCronEntityExceptionHandler.java src/main/java/com/bbcron/userservice/exceptions/UserNotFoundException.java src/main/java/com/bbcron/userservice/exceptions/UserPasswordException.java src/main/java/com/bbcron/userservice/exceptions/UserAlreadyExistException.java src/main/java/com/bbcron/userservice/exceptions/BBCronError.java src/main/java/com/bbcron/userservice/exceptions/UserNotCreatedException.java src/main/java/com/bbcron/userservice/BBCronUserServiceMain.java src/main/java/com/bbcron/userservice/domain/ALMStatusType.java src/main/java/com/bbcron/userservice/domain/UserDomain.java src/main/java/com/bbcron/userservice/domain/UserStatus.java src/main/resources/db/migration/V1.0__initial_account_schema.sql src/main/resources/application.yml src/main/resources/banner.txt src/main/resources/keycloak.json src/main/plantuml/CU-UserServices.puml src/main/plantuml/create/CU03-CreateUser.puml src/main/plantuml/create/CU03-CreateUser.png 'src/main/plantuml/create/DACU Create User.puml' 'src/main/plantuml/create/DACU Create User.png' src/main/plantuml/DCU-Actors.png src/main/plantuml/login/CU-LoginBBCron.png src/main/plantuml/login/CU-LoginBBCron.puml src/main/plantuml/DCU-Actors.puml src/main/plantuml/CU-UserServices.png .github/dependabot.yml .github/ISSUE_TEMPLATE/bug_Report.md .github/ISSUE_TEMPLATE/feature_request.md .github/workflows/semgrep.yml .github/workflows/maven.yml .github/workflows/mavenpublish.yml pom.xml` failed with exit code 7
30
31
This is an internal error, please file an issue at https://github.com/returntocorp/semgrep-action/issues/new/choose
32
and include any log output from above.
Run actions/upload-artifact@v2
0s
Post Run actions/checkout@v2
1s
Complete job
0s
```

**Expected behavior**
semgrep-action to finish without exiting.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Comment by colleend** [comment]
@benauca -- I've opened this issue to help track fixes. @benauca would you happen to know what priority this issue is for you?
