### ISSUE TITLE
Looks like semgrep raise a uncatch except

### ISSUE THREAD

**Issue by FrostNova2021** [returntocorp/semgrep#4689]
**Describe the bug**
Python Raise Except  --  IndexError: list index out of range

**To Reproduce**
Trying to use semgrep on virglrenderer ,and run this command
```
semgrep -e '$TYPE $FUNC(...){...}' --lang=c ~/Desktop/virglrenderer
```

**Expected behavior**
```
Not sending pseudonymous metrics since metrics are configured to AUTO and server usage is False
Traceback (most recent call last):
  File "/home/fuzzing/.local/bin/semgrep", line 8, in <module>
    sys.exit(main())
  File "/home/fuzzing/.local/lib/python3.8/site-packages/semgrep/__main__.py", line 20, in main
    cli()
  File "/home/fuzzing/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/fuzzing/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/fuzzing/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/fuzzing/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fuzzing/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/fuzzing/.local/lib/python3.8/site-packages/semgrep/commands/scan.py", line 813, in scan
    output_handler.output(
  File "/home/fuzzing/.local/lib/python3.8/site-packages/semgrep/output.py", line 290, in output
    output = self._build_output()
  File "/home/fuzzing/.local/lib/python3.8/site-packages/semgrep/output.py", line 390, in _build_output
    return self.formatter.output(
  File "/home/fuzzing/.local/lib/python3.8/site-packages/semgrep/formatter/base.py", line 26, in output
    return self.format(
  File "/home/fuzzing/.local/lib/python3.8/site-packages/semgrep/formatter/text.py", line 407, in format
    return "\n".join(itertools.chain(output, timing_output))
  File "/home/fuzzing/.local/lib/python3.8/site-packages/semgrep/formatter/text.py", line 375, in _build_text_output
    yield from TextFormatter._finding_to_line(
  File "/home/fuzzing/.local/lib/python3.8/site-packages/semgrep/formatter/text.py", line 95, in _finding_to_line
    indent_len = len(lines[0].rstrip()) - len(dedented_lines[0].rstrip())
IndexError: list index out of range
```

**Screenshots**
![20220217111532](https://user-images.githubusercontent.com/77134228/154398370-900f6573-7fc0-4792-bb9a-b80bf0d5f19c.png)

**What is the priority of the bug to you?**
- [ ] P0: blocking your adoption of Semgrep or workflow

**Environment**
official binary with pip install

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-881/looks-like-semgrep-raise-a-uncatch-except.

**Comment by ievans** [comment]
thanks for the bug report. I believe this is new as of semgrep 0.80 or newer - downgrading may unblock you for now. I've tagged as priority:high

**Comment by FrostNova2021** [comment]
Hi @ievans ,thans your reply and you are right .My semgrep version is 0.82.0

```
semgrep --version
0.82.0
```

This bug is very weird.
It will successful run and get result when i try found all function declare with '$TYPE $FUNC(...){...}' .
https://github.com/openslp-org/openslp/

![20220217114600](https://user-images.githubusercontent.com/77134228/154401280-c9591d5d-6fc4-4ef8-a0cb-7ffa219813a4.png)


However it can't work same command in this project.
https://github.com/freedesktop/virglrenderer

**Comment by ievans** [comment]
I will downgrade to priority:medium since there's a workaround, but @underyx or someone else will take a look

**Comment by ievans** [comment]
I've created a reproduction for this at https://semgrep.dev/s/RgbK but because playground uses the JSON output, not textual output, the specific exception isn't thrown.

@returntocorp/pa it looks like the core is returning a start location that is _after_ the end location. I'll update the output formatter to not assume that len(lines) != 0 but this definitely should be investigated:
```
RuleMatch(_id='-', _path=../../test-repos/virglrenderer/src/mesa/util/u_debug.c, _start=CoreLocation(line=453, col=1, offset=-1), _end=CoreLocation(line=452, col=7, offset=10823), _is_ignored=False, _lines=[], _lines_hash='e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', _previous_line='#endif\n')
```

**Comment by IagoAbal** [comment]
I did some minimization: https://semgrep.dev/s/n9RY

If we want this to be fixed in semgrep-core, shouldn't we reopen this issue?
